---
test:
  stage: test
  image: ruby:3
  script:
    - bash -n scripts/fetch-and-update \
        .ci/scripts/git-commit-changes \
        .ci/scripts/generate-pages-git-branch \
        .ci/scripts/git-push-branch
    - ruby -c scripts/create-json-files
  except:
    - master

deploy:
  stage: deploy
  image: ruby:3
  variables:
    NVDCVE_DIR: nvdcve
    MAIN_BRANCH: master
    PAGES_BRANCH: pages
  before_script:
    - git config user.name "GitLab CI Runner"
    - git config user.email "gitlab@example.com"
    - git checkout -b $CI_DEFAULT_BRANCH origin/$CI_DEFAULT_BRANCH || true
    - git pull --rebase origin $CI_DEFAULT_BRANCH
  script:
    # update NVD/CVE files by fetching the last archieve
    - scripts/fetch-and-update $NVDCVE_DIR

    # commit & push changes in git history
    - .ci/scripts/git-commit-changes $NVDCVE_DIR
    - .ci/scripts/git-push-branch $MAIN_BRANCH

    # generate & push pages branch
    - .ci/scripts/generate-pages-git-branch $NVDCVE_DIR $MAIN_BRANCH $PAGES_BRANCH
    - .ci/scripts/git-push-branch $PAGES_BRANCH -- -f
  only:
    - web
    - schedules
  timeout: 30m
  retry: 2
