#!/bin/bash

set -euxo pipefail

GIT_REMOTES="https://${GITHUB_TOKEN}@github.com/olbat/nvdcve,https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/olbat/nvdcve.git"

git_refspec=$1
shift
shift
git_args=$@

for git_remote in ${GIT_REMOTES//,/ }
do
	git push $git_args $git_remote $git_refspec
done
