#!/bin/bash

GIT_REMOTE="https://${GITHUB_TOKEN}@github.com/olbat/nvdcve"
GIT_BRANCH="master"

set -e
set -x

dir=${1:-nvdcve}

# if there is some changes in the repository: commit and push them
git add -N $dir
if ! git diff --exit-code $dir > /dev/null
then
	git commit -am "Automatic update"
	git remote set-url origin $GIT_REMOTE
	git push origin HEAD:$GIT_BRANCH
fi
