#!/bin/bash

GIT_REMOTE="https://${GITHUB_TOKEN}@github.com/olbat/nvdcve"
GIT_BRANCH="master"

set -e
set -x

dir=${1:-nvdcve}

# if there is some changes in the repository: commit, tag and push them
git add -N $dir
if ! git diff --exit-code $dir > /dev/null
then
	git commit -am "Automatic update"
	tag=$(date +%Y-%m-%d)
	git tag $tag

	git remote set-url origin $GIT_REMOTE
	git push origin HEAD:$GIT_BRANCH
	git push origin tag $tag
fi
