#!/bin/bash

GIT_REMOTES="https://${GITHUB_TOKEN}@github.com/olbat/nvdcve,https://${GITLAB_USER}:${GITLAB_TOKEN}@gitlab.com/olbat/nvdcve.git"

set -e
set -x

dir=${1:-nvdcve}

# if there are some changes in the repository: commit and push them
git add -N $dir
if ! git diff --exit-code $dir > /dev/null
then
	git commit -am "Automatic update"

	for git_remote in ${GIT_REMOTES//,/ }
	do
		git push $git_remote HEAD
	done
fi
