#!/bin/bash

set -euxo pipefail

MAIN_BRANCH=${MAIN_BRANCH:-master}

dir=${1:-nvdcve}
base_branch=${2:-master}
target_branch=${3:-pages}

git checkout --orphan $target_branch
git read-tree $(git rev-parse $base_branch:$dir)
git commit -m "Generate $target_branch branch from $dir directory on $base_branch branch"
